export type ContinuumErrorCode =
  | "CONTINUUM_PROJECT_NOT_FOUND"
  | "CONTINUUM_ALREADY_INITIALIZED"
  | "CONTINUUM_SCHEMA_INVALID"
  | "CONTINUUM_SCHEMA_TOO_NEW"
  | "CONTINUUM_GIT_UNAVAILABLE"
  | "CONTINUUM_GIT_UNBORN"
  | "CONTINUUM_RUNTIME_DRIVER_MISSING"
  | "CONTINUUM_RUNTIME_CORRUPT"
  | "CONTINUUM_CHANGE_NOT_FOUND"
  | "CONTINUUM_ARTIFACT_NOT_FOUND"
  | "CONTINUUM_ARTIFACT_CONFLICT"
  | "CONTINUUM_ARTIFACT_LOCATOR_INVALID"
  | "CONTINUUM_AUTHORITY_UNAVAILABLE"
  | "CONTINUUM_RELATION_NOT_FOUND"
  | "CONTINUUM_RELATION_ENDPOINT_NOT_FOUND"
  | "CONTINUUM_WORK_NOT_FOUND"
  | "CONTINUUM_WORK_AMBIGUOUS"
  | "CONTINUUM_WORK_CONFLICT"
  | "CONTINUUM_SNAPSHOT_CONFLICT"
  | "CONTINUUM_RECONCILE_NOT_FOUND"
  | "CONTINUUM_EVIDENCE_UNKNOWN"
  | "CONTINUUM_DECISION_REQUIRED"
  | "CONTINUUM_BLOCKED"
  | "CONTINUUM_CHANGE_NOT_READY"
  | "CONTINUUM_HOST_UNAVAILABLE"
  | "CONTINUUM_INTERACTION_NOT_FOUND"
  | "CONTINUUM_ARCHIVE_NOT_READY"
  | "CONTINUUM_ARCHIVE_EXISTS"
  | "CONTINUUM_ARCHIVE_INCOMPLETE"
  | "CONTINUUM_ARCHIVE_SOURCE_FAILED"
  | "CONTINUUM_ARCHIVE_HISTORY_FAILED"
  | "CONTINUUM_ARCHIVE_VERIFY_FAILED";

export class ContinuumError extends Error {
  constructor(
    public readonly code: ContinuumErrorCode,
    message: string,
    public readonly recoverable = false,
    public readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "ContinuumError";
  }
}
